name: Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          tox -e py${{ matrix.python-version }} --notest

      - name: Tests Python ${{ matrix.python-version }}
        run: |
          tox -e py${{ matrix.python-version }}

      - name: Mutation Tests
        run: |
          tox -e cosmic_ray

      - name: Archive mutation raport
        uses: actions/upload-artifact@v2
        with:
          name: mutation-report
          path: report.html
          retention-days: 1

      - name: CodeStyle
        run: |
          tox -e codestyle -e flake8
